package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* miércoles 10 de junio de 2020 03:02:38 AM CDT
*/

public interface HelloOperations 
{
  String sayHello (String mensaje);
  String operacionMat (String operacion);
  void mandarMensaje (String mensaje);
  String checarUltimoMsj ();
  void mandarArchivo (String archivo);
  void shutdown ();
} // interface HelloOperations
